export default {
  drinks: [
    {
      idDrink: '11000',
      strDrink: 'Mojito',
      strDrinkAlternate: null,
      strTags:
        'IBA,ContemporaryClassic,Alcoholic,USA,Asia,Vegan,Citrus,Brunch,Hangover,Mild',
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions:
        'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
      strInstructionsES: null,
      strInstructionsDE:
        'Minzblätter mit Zucker und Limettensaft verrühren. Füge einen Spritzer Sodawasser hinzu und fülle das Glas mit gebrochenem Eis. Den Rum eingießen und mit Sodawasser übergießen. Garnieren und mit einem Strohhalm servieren.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Pestare le foglie di menta con lo zucchero e il succo di lime.\r\nAggiungere una spruzzata di acqua di seltz e riempi il bicchiere con ghiaccio tritato.\r\nVersare il rum e riempire con acqua di seltz.\r\nGuarnire con una fetta di lime, servire con una cannuccia.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
      strIngredient1: 'Light rum',
      strIngredient2: 'Lime',
      strIngredient3: 'Sugar',
      strIngredient4: 'Mint',
      strIngredient5: 'Soda water',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2-3 oz ',
      strMeasure2: 'Juice of 1 ',
      strMeasure3: '2 tsp ',
      strMeasure4: '2-4 ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource:
        'https://pixabay.com/photos/cocktail-mojito-cocktail-recipe-5096281/',
      strImageAttribution:
        'anilaha https://pixabay.com/users/anilaha-16242978/',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-11-04 09:17:09',
    },
    {
      idDrink: '11007',
      strDrink: 'Margarita',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions:
        'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
      strInstructionsES: null,
      strInstructionsDE:
        'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
      strIngredient1: 'Tequila',
      strIngredient2: 'Triple sec',
      strIngredient3: 'Lime juice',
      strIngredient4: 'Salt',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource:
        'https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg',
      strImageAttribution: 'Cocktailmarler',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 14:42:59',
    },
    {
      idDrink: '11003',
      strDrink: 'Negroni',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic',
      strVideo: 'https://www.youtube.com/watch?v=Y4LH0FQlU8Q',
      strCategory: 'Ordinary Drink',
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions: 'Stir into glass over ice, garnish and serve.',
      strInstructionsES: null,
      strInstructionsDE:
        'In ein Glas über das Eis gießen, garnieren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Mescolare nel bicchiere con ghiaccio, guarnire e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Campari',
      strIngredient3: 'Sweet Vermouth',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://www.thecocktaildb.com/drink/11003',
      strImageAttribution: 'TheCocktailDB.com',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 15:12:07',
    },
    {
      idDrink: '11004',
      strDrink: 'Whiskey Sour',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic,Alcoholic,ContemporaryClassic',
      strVideo: 'https://www.youtube.com/watch?v=hFKZPzfngcU',
      strCategory: 'Ordinary Drink',
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions:
        "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
      strInstructionsES: null,
      strInstructionsDE:
        'Mit Eis schütteln. In ein gekühltes Glas abseihen, garnieren und servieren. Wenn Sie "On the rocks" servieren, die Zutaten in ein old-fashioned, mit Eis gefülltes Glas geben.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Shakerare con ghiaccio.Filtrare in un bicchiere freddo, guarnire e servire.Se servito "On the rocks", filtra gli ingredienti in un bicchiere vecchio stile pieno di ghiaccio.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg',
      strIngredient1: 'Blended whiskey',
      strIngredient2: 'Lemon',
      strIngredient3: 'Powdered sugar',
      strIngredient4: 'Cherry',
      strIngredient5: 'Lemon',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: 'Juice of 1/2 ',
      strMeasure3: '1/2 tsp ',
      strMeasure4: '1 ',
      strMeasure5: '1/2 slice ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource:
        'https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0191.jpg',
      strImageAttribution:
        'Ralf Roletschek https://www.wikidata.org/wiki/Q15080600',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-02 12:45:25',
    },
    {
      idDrink: '11002',
      strDrink: 'Long Island Tea',
      strDrinkAlternate: null,
      strTags: 'Strong,Asia,StrongFlavor,Brunch,Vegetarian,Sour',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions:
        'Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.',
      strInstructionsES: null,
      strInstructionsDE:
        'Alle Zutaten (außer Cola) mischen und in einem Highball-Glas über Eis gießen. Füge einen Spritzer Cola hinzu, um Farbe zu erhalten. Mit einer Scheibe Zitrone dekorieren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Unisci tutti gli ingredienti (tranne la cola) e versa il ghiaccio in un bicchiere highball. Aggiungi la spruzzata di cola per il colore. Decorare con una fetta di limone e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/nkwr4c1606770558.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Light rum',
      strIngredient3: 'Gin',
      strIngredient4: 'Tequila',
      strIngredient5: 'Lemon',
      strIngredient6: 'Coca-Cola',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1/2 oz ',
      strMeasure4: '1/2 oz ',
      strMeasure5: 'Juice of 1/2 ',
      strMeasure6: '1 splash ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://pxhere.com/en/photo/1593200',
      strImageAttribution:
        'Irina Prokopenko https://pxhere.com/en/photographer/999895',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 14:54:32',
    },
    {
      idDrink: '11006',
      strDrink: 'Daiquiri',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic,Beach',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions:
        'Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.',
      strInstructionsES: null,
      strInstructionsDE:
        'Alle Zutaten in den Shaker mit Eiswürfel geben. Gut schütteln. In einem gekühlten Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Versare tutti gli ingredienti nello shaker con cubetti di ghiaccio.Filtrare in una coppetta da cocktail ghiacciata. Agitare bene',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg',
      strIngredient1: 'Light rum',
      strIngredient2: 'Lime',
      strIngredient3: 'Powdered sugar',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: 'Juice of 1/2 ',
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource:
        'https://commons.wikimedia.org/wiki/File:Classic_Daiquiri_in_Cocktail_Glass.jpg',
      strImageAttribution: 'Will Shenton',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 15:06:37',
    },
    {
      idDrink: '11001',
      strDrink: 'Old Fashioned',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic,Alcoholic,Expensive,Savory',
      strVideo: 'https://www.youtube.com/watch?v=YsE_igrPXZs',
      strCategory: 'Cocktail',
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions:
        'Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.',
      strInstructionsES: null,
      strInstructionsDE:
        'Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser hinzufügen. Vermischen, bis sie sich auflösen.',
      strInstructionsFR: null,
      strInstructionsIT:
        "Mettere la zolletta di zucchero nel bicchiere vecchio stile e saturare con il bitter, aggiungere un goccio di acqua naturale.\r\nPestare finché non si scioglie.\r\nRiempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky.\r\nGuarnire con una scorza d'arancia e una ciliegina al maraschino.",
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
      strIngredient1: 'Bourbon',
      strIngredient2: 'Angostura bitters',
      strIngredient3: 'Sugar',
      strIngredient4: 'Water',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4.5 cL',
      strMeasure2: '2 dashes',
      strMeasure3: '1 cube',
      strMeasure4: 'dash',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource:
        'https://www.thecocktaildb.com/drink/11001-Old-Fashioned-Cocktail',
      strImageAttribution: 'Dave M',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-11-04 09:46:42',
    },
    {
      idDrink: '11005',
      strDrink: 'Dry Martini',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic,Christmas,Alcoholic',
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions:
        'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
      strInstructionsES: null,
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT:
        "Dritto: Versare tutti gli ingredienti nel mixing glass con cubetti di ghiaccio. Mescolare bene. Filtrare in una coppetta da cocktail Martini ghiacciata. Spremi l'olio della scorza di limone sulla bevanda o guarnisci con l'oliva.",
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Dry Vermouth',
      strIngredient3: 'Olive',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 2/3 oz ',
      strMeasure2: '1/3 oz ',
      strMeasure3: '1 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://www.thecocktaildb.com/drink/11005',
      strImageAttribution: 'TheCocktailDB.com',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-02 12:51:35',
    },
  ],
};
